corazawaf/coraza-spoa

doc/config/coraza.cfg, doc/config/haproxy.cfg
coraza-spoa
- Increase processing timeout to 500ms
- Set an error variable, in case of timeouts
haproxy
- Use timeouts from official haproxy sample config
-  Add a log format which includes a waf-hit and spoa error variable
-  Deny requests in case of a abnormal/unexpected spoa error/timeout by default. Otherwise Coroza WAF is simply disabled.
-  Provide a sample config, which does not require a backend, but rather simply reply using static content.
=> Update sample configs

internal/request.go, internal/response.go, internal/spoa.go
- Cache wasn't been cleaned by interrupted responses
- Cache was created for interrupted requests and we had to wait for the TTL to log
Thanks for the report @sts 
#11
=> Fix cache clean (closes #11)

doc/config/coraza.cfg, internal/request.go
- Includes the information in the transaction audit log record
- Populates the engine rule variables
fixes #16
=> Include source port, destination ip & port in processConnection

.github/workflows/package.yaml, Makefile
Introduce Github Actions for building Binaries & Debian Package
Github Actions
Github Ubuntu 22.04
Go 1.18.2
Builds are performed using matrix jobs, each job creates a package for a supported platform. Currently configured are: amd64, arm64
A commit is merged to the main branch, a test version automatically gets built. The package is versioned with the current date, hour, minute and git hash of the commit. Example:
`coraza-spoa-202206210000-81d12f7_amd64.deb`
The package is then pushed to the snapshot repository and allows a user to perform testing. Steps:
- Change the repo in apt/sources.list
- Install a snapshot version: `apt install -t coraza-spoa=202206210000-81d12f7`
A git tag is created. The tag follows semver semantics (eg. v0.0.1). A release package automatically gets built. The …
=> Adding github workflow to build & publish Debian packages

config/config.go, internal/spoa.go
Now coraza error (events) logs will be forwarded to /dev/stdout and a file
=> add error log support

internal/spoa.go
- ARC algorithm requires a TTL
- Evict function will only work with TTL
- I replaced ARC (LFU+LRU) with LFU, LFU is better for our use case as it will evict old objects
- I added the cache from the settings
=> change eviction algorithm and apply ttl (Fix #15)

.github/workflows/container-image.yaml
Ref: #37 
This PR copies the github action from https://github.com/corazawaf/coraza-proxy-wasm/blob/main/.github/workflows/ci.yaml with some modifications to work in this repo.
This action will build and push an image to GHCR based on the Dockerfile in the root of the repo for every push to `main` and for every tag push.
Example of it working: https://github.com/mac-chaffee/coraza-spoa/actions/runs/3578128681/jobs/6017925537
Example image: https://github.com/mac-chaffee/coraza-spoa/pkgs/container/coraza-spoa
=> Add github action to push container image

.github/workflows/container-image.yaml, Dockerfile, docker-compose.e2e.yaml, docker-compose.yaml, docker/coraza-spoa/coraza.conf, docker/coraza-spoa/docker-entrypoint.sh, go.mod
- Run coraza-spoa as unprivileged user within the container
- Device images in a main image without CRS and a coreruleset target to include CRS
- Add multiarch images for multiple platforms
- Use docker-entrypoint.sh
- Use tini
=> chore: upgrades coraza docker

internal/spoa.go
Closes #79.
```
coraza-spoa-coraza-1   | {"level":"error","ts":1689808068.161278,"msg":"[client \"172.18.0.1\"] Coraza: Access denied (phase 2). Inbound Anomaly Score Exceeded (Total Score: 10) [file \"/etc/coraza-spoa/rules/REQUEST-949-BLOCKING-EVALUATION.conf\"] [line \"9504\"] [id \"949110\"] [rev \"\"] [msg \"Inbound Anomaly Score Exceeded (Total Score: 10)\"] [data \"\"] [severity \"emergency\"] [ver \"OWASP_CRS/4.0.0-rc1\"] [maturity \"0\"] [accuracy \"0\"] [tag \"anomaly-evaluation\"] [hostname \"172.18.0.4\"] [uri \"/?x=/etc/passwd\"] [unique_id \"35c2afb4-14ea-4522-8273-724412d9d3ad\"]\n"}
```
=> Fixed IPs to string convertation

docker-compose.e2e.yaml, docker/e2e/Dockerfile.curl, docker/e2e/e2e.sh, docker/haproxy/haproxy.cfg, internal/spoa.go
Closes #73 
[log.txt](https://github.com/corazawaf/coraza-spoa/files/12031229/log.txt)
=> Fixed allowing action & HAProxy logging

README.md, config.yaml.default, doc/config/coraza.cfg, doc/config/haproxy.cfg
- Add an updated haproxy configuration example, and remove usage of `txn.coraza.fail`
- Update sample timeouts based upon comments from https://github.com/haproxy/haproxy/blob/master/doc/SPOE.txt#L604
- Disable the transaction cache by default, until we know its running stable
=> Update documenation to avoid errors

doc/config/coraza.cfg, docker/haproxy/coraza.cfg
Building the docker image failed on two issues:
- since 8f29491 coraza.cfg didn't fit the coraza version anymore. It was only updated in the doc folder
- haproxy starting with 2.3 requires a LF at the end of config files, that was also missing.
=> Fix image build

internal/spoa.go
Use the OS stdout and stderr for /dev/stdout and
/dev/stderr.
I case of systemd stdout and stderr might be redirected to a unix socket and the file open fails.
Using the OS stdout and stderr avoids that problem.
Signed-Off-By: Sven Auhagen <sven.auhagen@voleatech.de>
=> File logging: stdout and stderr

.github/workflows/lint.yaml, .github/workflows/package.yaml, .github/workflows/test.yaml
Also use the correct go version for building the package, and not the version from the system (Ubuntu 24.04)
Fixes #146
=> test: use go version from go.mod

.github/workflows/container-image.yaml, .github/workflows/lint.yaml, .github/workflows/package.yaml, .github/workflows/test.yaml
haproxy 2.8 is not available for ubuntu 24.04. We should downgrade to 22.04 until we have migrated our builds to a matrix build
=> ci: replace ubuntu-latest with ubuntu-22.04

main.go
This PR adds what was attempted in https://github.com/corazawaf/coraza-spoa/pull/110
But the reasoning is different. 
Now, the app does not pick up an invalid config on reload, which is awesome.
Still, the admin might need a way to validate another testing or staging config without messing around with the current one. This could be useful for testing or used by external config builders.
=> Add config validate flag

main.go
It would be nice to see how long the config reload takes in deployments with many applications (especially without memoize).
=> Log the end of successful config reload event

config.go, main.go
I realized that in https://github.com/corazawaf/coraza-spoa/pull/208 I forgot to add logging to config watcher as well.
Alternatively, I could move this log message to `reloadConfig()` to avoid repeating code.
=> Log successful reload on config update

example/haproxy/haproxy.cfg
Thanks @jcrood for pointing this one out.
Closes #71
=> docs: fix wrong variable name in haproxy.cfg

.github/workflows/container-image.yaml
The release-please action creates tagged PRs that contain only changes to CHANGELOG.md
So, the image build action will never run after we merge a release-please PR.
This PR tries to rectify this issue and additionally avoid unnecessary image builds by limiting the paths.
=> ci: fix container image build workflow

config.go, internal/application.go
Previously the json handler would only wrap the message in a json object. This now replaces that message with an embedded object that contains all the information.
Thanks to @superstes for implementing this in his fork
=> feat: print matched error logs as json if requested
